#ifdef DEF_SYSCALL
// System call numbers
DEF_SYSCALL(1, fork)
DEF_SYSCALL(2, exit)
DEF_SYSCALL(3, wait)
DEF_SYSCALL(4, pipe)
DEF_SYSCALL(5, read)
DEF_SYSCALL(6, kill)
DEF_SYSCALL(7, exec)
DEF_SYSCALL(8, fstat)
DEF_SYSCALL(9, chdir)
DEF_SYSCALL(10, dup)
DEF_SYSCALL(11, getpid)
DEF_SYSCALL(12, sbrk)
DEF_SYSCALL(13, sleep)
DEF_SYSCALL(14, uptime)
DEF_SYSCALL(15, open)
DEF_SYSCALL(16, write)
DEF_SYSCALL(17, mknod)
DEF_SYSCALL(18, unlink)
DEF_SYSCALL(19, link)
DEF_SYSCALL(20, mkdir)
DEF_SYSCALL(21, close)
DEF_SYSCALL(22, trace)
DEF_SYSCALL(23, pgaccess)
#endif